import Head from 'next/head'
import { Inter } from '@next/font/google'
import Image from 'next/image';
import { motion } from "framer-motion";
import { useRouter } from 'next/router';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>RMN's Cafe</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/cute-cat.gif" type='image/gif'/>
      </Head>
      <main className="p-9 bg-black h-[100vh] w-[100vw] flex flex-col justify-center items-center">
        <div className="bg-teal-800 w-[80vw] h-[80vh] relative flex justify-between items-center">
          <motion.div animate={{height: 0}}
                      transition={{ duration: 2, ease: "easeInOut" }}
                      className="absolute h-full w-full top-0 left-0 bg-black z-10">
          </motion.div>
          <div className="h-full w-1/2 flex flex-col pl-10 pr-5 overflow-hidden justify-center">
            <motion.h1 initial={{ x: "-30%", opacity: 0 }} animate={{ x: 0, opacity: 1 }} transition={{duration: 1, delay: 0.7}} className="uppercase flex-col mb-5 items-center justify-center text-start  text-white font-bold text-3xl animate-scale z-0">
              rmn's cafe 
            </motion.h1>
            <div className="buttons gap-9 grid grid-cols-3">
              <motion.button whileTap={{ opacity: 0.7 }} whileHover={{ scale: 0.93 }} className='px-5 my-2 pixel-border bg-teal'>Projects</motion.button>
              <motion.button whileTap={{ opacity: 0.7 }}  whileHover={{ scale: 0.93 }} className='px-5 my-2 pixel-border bg-teal' onClick={(e) => {router.push("/about")}}>About</motion.button>
              <motion.button whileTap={{ opacity: 0.7 }}  whileHover={{ scale: 0.93 }} className='px-5 my-2 pixel-border bg-teal'>Contacts</motion.button>
              <motion.button whileTap={{ opacity: 0.7 }}  whileHover={{ scale: 0.93 }} className='px-5 my-2 pixel-border bg-teal'>Blogs</motion.button>
              <motion.button whileTap={{ opacity: 0.7 }}  whileHover={{ scale: 0.93 }} className='px-5 my-2 pixel-border bg-teal'>Register</motion.button>
            </div>
          </div>
          <div className="h-full w-1/2 flex flex-col items-center justify-center">
            <div className="h-full flex flex-col justify-center">
              <motion.div whileTap={{ opacity: 0.5 }} whileHover={{ scale: 0.93 }}>
                <Image src={"/cute-cat.gif"} alt="cat :3" width={250} height={250} style={{ transform: "scaleX(-1)" }} />
              </motion.div>
              <motion.p initial={{ x: "-30%", opacity: 0 }} animate={{ x: 0, opacity: 1 }} transition={{duration: 1, delay: 2.7}} className="p-5 flex-col items-center justify-center  text-white font-bold text-3xl animate-scale z-0">
                this ^ is armaan btw
              </motion.p>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
